CT-1234 background reports
ministryofjustice/correspondence_tool_staff pull request #16
Opened 2017-12-22 12:38 UTC by misaka

2017-12-28 09:23 UTC, aliuk2012 commented on app/models/report_type.rb
> +  def class_constant
this hasn't been tested.

2017-12-28 09:33 UTC, aliuk2012 requested changes
LGTM apart from the one small missing spec in report type model

2017-12-29 11:14 UTC, stephenrichards approved these changes

2017-12-29 12:22 UTC, aliuk2012 approved these changes

2018-01-02 10:07 UTC, misaka commented
Rebased to squash and reword commits.

2018-01-02 10:21 UTC, merged