CT-3756 Add data received date into data request
ministryofjustice/correspondence_tool_staff pull request #1680
Opened 2021-08-10 08:25 UTC by ymao2

## Description

This PR is to add the date of recording when the data is received into data request
## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [X] (3) Tests passing
* [X] (4) Branch ready to be merged (not work in progress)
* [X] (5) No superfluous changes in diff
* [X] (6) No TODO's without new ticket numbers
* [X] (7) PR Prefixed with ticket number e.g. `CT-7654 ...`

### Screenshots

### Related JIRA tickets

https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&modal=detail&selectedIssue=CT-3756
### Deployment

### Manual testing instructions

2021-08-13 14:37 UTC, willmcb commented
<img width="204" alt="Screenshot 2021-08-13 at 15 37 42" src="https://user-images.githubusercontent.com/13377553/129373802-27f3948c-8b20-42d3-8b94-bf32215df286.png">

2021-08-13 14:40 UTC, willmcb requested changes
One small change! Otherwise looks really good and works well.

2021-08-13 14:42 UTC, willmcb approved these changes

2021-08-18 10:01 UTC, ymao2 commented
> <img alt="Screenshot 2021-08-13 at 15 37 42" width="204" src="https://user-images.githubusercontent.com/13377553/129373802-27f3948c-8b20-42d3-8b94-bf32215df286.png">
> 
> Looks really good, nice work! 👍 I think this branch introduces this small UI bug (compared to main):
> 
> <img alt="Screenshot 2021-08-13 at 15 39 34" width="258" src="https://user-images.githubusercontent.com/13377553/129374023-d346b216-bc4d-484a-939c-24043a98925b.png">

just checked, this black line is for the second screenshot , not the first one, so the UI isn't broken 😄

2021-08-18 10:02 UTC, merged