Ct 1670 filter by deadline
ministryofjustice/correspondence_tool_staff pull request #183
Opened 2018-05-04 09:38 UTC by beccapearce

2018-05-04 10:52 UTC, aliuk2012 requested changes

2018-05-04 10:52 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +              - today = {day: @query.available_deadlines[:today].strftime("%d"), month: @query.available_deadlines[:today].strftime("%m"), year: @query.available_deadlines[:today].strftime("%Y")}.to_
Can't we set these values in the action or service? I don't think the view is the best place to have them.

2018-05-04 10:52 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +              - days_3 = {day: @query.available_deadlines[:three_days].strftime("%d"), month: @query.available_deadlines[:three_days].strftime("%m"), year: @query.available_deadlines[:three_days].str
Can't we set these values in the action or service?

2018-05-04 10:52 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +              - days_10 = {day: @query.available_deadlines[:ten_days].strftime("%d"), month: @query.available_deadlines[:ten_days].strftime("%m"), year: @query.available_deadlines[:ten_days].strftime
Can't we set these values in the action or service?

2018-05-04 10:52 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +      .form-group
We can remove this, v3 of the date field gems now includes it

2018-05-04 10:52 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +      .form-group
We can remove this, v3 of the date field gems now includes it

2018-05-04 11:42 UTC, stephenrichards requested changes

2018-05-04 11:42 UTC, stephenrichards commented on app/services/case_search_service.rb
> +                               end
Don't we need to take like 77 out ?

2018-05-04 11:42 UTC, stephenrichards commented on spec/lib/papertrail_spec.rb
> +    it 'restores the gov_uk_dates' do
Great!  I think we need to update the readme too on this - I think it specifically says that gov_uk dates don't work and gives a work-around.

2018-05-08 09:26 UTC, aliuk2012 commented on app/views/cases/search_filters/_final_deadline.html.slim
> +      .form-group
We agreed to ignore this for the time being there does seem to be a bug with the govuk date gem where its displaying the fields along side each other.

2018-05-08 10:08 UTC, stephenrichards approved these changes

2018-05-09 09:40 UTC, aliuk2012 approved these changes

2018-05-09 09:41 UTC, merged