CT-1403 Allow BMT users to edit open SAR cases
ministryofjustice/correspondence_tool_staff pull request #218
Opened 2018-05-31 10:31 UTC by stephenrichards

2018-05-31 11:21 UTC, misaka approved these changes
Nice one.

2018-05-31 11:24 UTC, misaka requested changes
Actually, I just realised ... no feature tests?

2018-05-31 14:23 UTC, beccapearce requested changes
Could I be a pain and get you to change it in the spec/features/user_journeys/sar/non_trigger_spec.rb too, the steps are there but commented out

2018-05-31 15:44 UTC, beccapearce approved these changes

2018-06-01 09:16 UTC, misaka approved these changes

2018-06-02 10:36 UTC, merged