cdpt 761 ct migrate to circleci credentials
ministryofjustice/correspondence_tool_staff pull request #2227
Opened 2023-06-30 09:52 UTC by MeenaModhvadia

## Description

## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [ ] (3) Tests passing
* [ ] (4) Branch ready to be merged (not work in progress)
* [ ] (5) No superfluous changes in diff
* [ ] (6) No TODO's without new ticket numbers
* [ ] (7) PR Prefixed with ticket number e.g. `CT-7654 ...`
* [ ] (8) Data migration script is created if any of letter templates is changed

### Screenshots

### Related JIRA tickets

### Deployment

### Manual testing instructions

2023-07-04 16:44 UTC, vertism commented on .circleci/config.yml
> +        ./deploy.sh $build_tag qa circleci
```suggestion
        ./deploy.sh $build_tag development circleci
```

2023-07-04 16:46 UTC, vertism commented on .circleci/config.yml
> +  deploy_main_to_dev: *do_dev_deployment_tasks
```suggestion
```

2023-07-04 16:53 UTC, MeenaModhvadia commented on .circleci/config.yml
> +  deploy_main_to_dev: *do_dev_deployment_tasks
Thanks - removed

2023-07-04 16:53 UTC, MeenaModhvadia commented on .circleci/config.yml
> +        ./deploy.sh $build_tag qa circleci
Thanks - corrected

2023-07-05 08:54 UTC, vertism commented on .circleci/config.yml
> +
Add this back in to speed up the testing section
```suggestion
    resource_class: xlarge
    
```

2023-07-05 09:41 UTC, vertism commented on .circleci/config.yml
> +  jobs:
```suggestion
jobs:
```

2023-07-05 09:41 UTC, vertism commented on .circleci/config.yml
> +    build_branch_and_push_to_ecr:
```suggestion
  build_branch_and_push_to_ecr:
```

2023-07-05 16:18 UTC, vertism commented on .circleci/config.yml
> +        - *upload_test_coverage
```suggestion
      - checkout
      - *restore_cache
      - *install_bundler
      - *check_bundler_version
      - *install_psql
      - *install_dependencies
      - *save_cache
      - *wait_for_db
      - *set_up_the_database
      - *rubocop
      - *update_chromedriver
      - *setup_test_reporter
      - *run_unit_and_feature_tests
      - *upload_test_coverage
```

2023-07-05 16:20 UTC, vertism commented on .circleci/config.yml
> +      #       - deploy_main_to_demo_approval
I don't think this needs to change, you can revert it back to the original code on the left.

2023-07-05 16:21 UTC, vertism commented on .circleci/config.yml
> +            ignore: main
This doesn't need to change, it's correctly indented on the left.

2023-07-06 07:40 UTC, lucas-shaw approved these changes
LGTM

2023-07-06 08:02 UTC, vertism requested changes
A couple of indent issues to deal with

2023-07-06 09:20 UTC, vertism commented on .circleci/config.yml
> +              - build_tag
@MeenaModhvadia I think this is the last thing that needs updating :)

2023-07-06 09:38 UTC, vertism commented on .circleci/config.yml
> +          - build_tag
```suggestion
            - build_tag
```

2023-07-06 09:52 UTC, vertism approved these changes

2023-07-11 15:09 UTC, merged