ct-1849 add message to overturned sar
ministryofjustice/correspondence_tool_staff pull request #416
Opened 2018-09-03 10:57 UTC by beccapearce

2018-09-03 12:02 UTC, misaka commented on spec/features/cases/overturned_sar/add_message_to_case_spec.rb
> +feature 'SAR Case creation by a manager' do
Old feature text in here.

2018-09-03 12:21 UTC, misaka requested changes
I think the test should either be part of the end-to-end journey or rely on a factory.

2018-09-06 09:14 UTC, misaka approved these changes

2018-09-06 10:06 UTC, misaka commented
Do not merge until we get CT-1914 done.

2018-09-06 12:59 UTC, aliuk2012 commented
#422 has been merged

2018-09-06 14:05 UTC, merged