Ct 1876 non trigger extend for pit
ministryofjustice/correspondence_tool_staff pull request #417
Opened 2018-09-03 14:55 UTC by beccapearce

2018-09-03 15:29 UTC, beccapearce commented on config/state_machine/moj.yml
> +                #   if: Workflows::Predicates#new_overturned_ico?
there is a naming issue with this in master

2018-09-05 09:47 UTC, stephenrichards requested changes
Code OK.
Although I can see what has been done, I think we should have a summary of what the issue was and what we did to resolve it on the commit message and/or ticket itself.

2018-09-06 14:06 UTC, misaka approved these changes

2018-09-06 14:42 UTC, stephenrichards approved these changes

2018-09-06 16:13 UTC, merged