Ct 2028 approver emails not sending
ministryofjustice/correspondence_tool_staff pull request #671
Opened 2019-02-12 11:31 UTC by beccapearce

Updates methods names to be clearer as to teams being emailed, add notification messages that have the correct team name

2019-02-15 11:02 UTC, mseedat-moj requested changes
Few minor issues as commented and a few strings that should have single quotes rather than double quotes to remain consistent with the code around it. Otherwise looks good

2019-02-15 11:02 UTC, mseedat-moj commented on spec/features/cases/foi/case_approvals/press_office_approvals_spec.rb
> +                      expected_notice: "Private Office has been notified that the response is pending clearance."
Minor - using double quotes for the string rather than single quotes

2019-02-15 11:02 UTC, mseedat-moj commented on spec/features/cases/foi/case_approvals/press_office_approvals_spec.rb
> +                      expected_notice: "Press Office has been notified that the response is pending clearance."
Minor - using double quotes for the string rather than single quotes

2019-02-15 11:02 UTC, mseedat-moj commented on spec/features/cases/foi/case_approvals/private_office_approvals_spec.rb
> +                      expected_notice: "Private Office has been notified that the response is pending clearance."
Minor - using double quotes for the string rather than single quotes

2019-02-15 11:04 UTC, beccapearce commented on app/mailers/action_notifications_mailer.rb
> +        case_subject:           kase.subject,
yes, it matches the order in notify, I'm hoping it will make tracking down issues easier in the future

2019-02-15 11:11 UTC, mseedat-moj commented on app/services/response_uploader_service.rb
> +          .ready_for_press_or_private_review( assignment )
Spaces around the parameter variable

2019-02-15 12:48 UTC, mseedat-moj approved these changes
Looks good, had convo about approver vs press_and_private_reviewer roles being distinct - out of scope for this ticket.

2019-02-18 15:56 UTC, beccapearce commented
Conversation about approver vs press_and_private_reviewer roles being distinct is still to take place

2019-02-18 15:56 UTC, merged