Ct 2151 user cant navigate to page2
ministryofjustice/correspondence_tool_staff pull request #722
Opened 2019-03-26 13:02 UTC by starswan

added a unique index to prevent constraint being violated again. 5 duplicates in production deleted to enable user to get going again

2019-03-26 14:03 UTC, beccapearce commented on db/migrate/20190326113949_add_unique_index_to_user_case_transition_tracker.rb
> +    change_table :cases_users_transitions_trackers do |t|
Could we add the timestamp to Cases users transitions trackers?

2019-03-26 14:04 UTC, beccapearce requested changes
Request for adding time stamps to cases users transitions tracker

2019-03-27 10:18 UTC, beccapearce approved these changes

2019-04-03 11:06 UTC, mseedat-moj commented
Recommend saving this merge once deployment to Development for previous sprint is proven to work - too many broken/moving parts as of this moment making me feel anxious. Please hold off until Dev/Staging/Prod are proven to work again.

2019-04-10 15:41 UTC, merged