CT-2266 Close offender SAR case
ministryofjustice/correspondence_tool_staff pull request #870
Opened 2019-08-10 11:44 UTC by Polsonby

## Description
Use existing pattern for closing a case instead of "Mark as closed":

![image](https://user-images.githubusercontent.com/1161161/62821421-8bedf280-bb6c-11e9-9f2e-23f92a568e46.png)

![image](https://user-images.githubusercontent.com/1161161/62821423-90b2a680-bb6c-11e9-9ebc-ebe8ac89402e.png)

 
## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [ ] (3) Tests passing
* [ ] (4) Branch ready to be merged (not work in progress)
* [ ] (5) No superfluous changes in diff
* [ ] (6) No TODO's without new ticket numbers
 
### Screenshots

 
### Related JIRA tickets

 
### Deployment

 
### Manual testing instructions

2019-08-29 14:37 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
> -
Not related to this PR per se, but cleaned up some redundant code, partly left from merging work

2019-09-03 07:59 UTC, mseedat-moj requested changes
almost there minor requests

2019-09-03 08:28 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
> +        close
This work was to change to use an existing behaviour with an existing name. We don't want to change it everywhere else :)

2019-09-03 08:28 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
>      include GovUKDateFixes
Let's do that, but not in this PR 👍

2019-09-03 08:29 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
>      before_action :set_date_of_birth, except: [:new, :create]
Separate PR IMO

2019-09-03 16:18 UTC, Polsonby commented on app/views/cases/offender_sar/_closure_outcomes_form.html.slim
> +        = f.submit submit_button, {class: 'button'}
Fixed, thanks

2019-09-03 16:18 UTC, Polsonby commented on app/views/cases/offender_sar/_closure_outcomes_form.html.slim
> +
fixed, thanks

2019-09-03 16:18 UTC, Polsonby commented on app/controllers/cases_controller.rb
> +    :transition
Done :) 👍

2019-09-03 16:19 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
>      before_action :set_date_of_birth, except: [:new, :create]
Hah - this is funny - turned out the order of the before action statements was what was messing me up, in particular the set date of birth one - so removed as originally proposed!

2019-09-03 16:22 UTC, Polsonby reviewed
@mseedat-moj Implemented suggestions, please can you re-review?

2019-09-03 16:22 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
>      include GovUKDateFixes
See other comment - turned out this WAS an excellent time to do it, thanks!

2019-09-03 16:22 UTC, Polsonby commented on app/controllers/cases/offender_sar_controller.rb
> +        close
Turns out to be an awkward place to put a comment - I think it's fine without the comment tbh 👍

2019-09-03 16:49 UTC, mseedat-moj approved these changes
Top bommy

2019-09-04 07:11 UTC, merged