CT-2404 Replace empty name with subject on closed case table
ministryofjustice/correspondence_tool_staff pull request #904
Opened 2019-09-03 13:48 UTC by digitalali-moj

## Description

 
## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [ ] (3) Tests passing
* [ ] (4) Branch ready to be merged (not work in progress)
* [ ] (5) No superfluous changes in diff
* [ ] (6) No TODO's without new ticket numbers
 
### Screenshots

 
### Related JIRA tickets

 
### Deployment

 
### Manual testing instructions

2019-09-04 21:29 UTC, mseedat-moj requested changes

2019-09-04 21:29 UTC, mseedat-moj commented on app/views/cases/filters/closed.html.slim
> +                = kase.name == '' ? kase.subject : kase.name
Apologies forgot to actually press the 'submit' button!

2019-09-06 16:36 UTC, digitalali-moj commented on spec/decorators/case/base_decorator_spec.rb
> +        expect(closed_case_name(kase)).to eq 'Monalisa Khan'
Not quite working yet, WIP

2019-09-11 09:25 UTC, digitalali-moj commented on spec/decorators/case/base_decorator_spec.rb
> +        expect(closed_case_name(kase)).to eq 'Monalisa Khan'
Working now after patch

2019-09-11 16:28 UTC, mseedat-moj approved these changes
Well done

2019-09-11 17:32 UTC, merged